// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: val
func (_m *MockDB) Get(val string) string {
	ret := _m.Called(val)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(val)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDB_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDB_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - val string
func (_e *MockDB_Expecter) Get(val interface{}) *MockDB_Get_Call {
	return &MockDB_Get_Call{Call: _e.mock.On("Get", val)}
}

func (_c *MockDB_Get_Call) Run(run func(val string)) *MockDB_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDB_Get_Call) Return(_a0 string) *MockDB_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDB_Get_Call) RunAndReturn(run func(string) string) *MockDB_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
